package com.myt.ui.theme

import androidx.compose.ui.graphics.Color

/** Instrument cluster & glass panel palette extensions on [GaugeColors]. */
val GaugeColors.clusterBezelOuter: Color get() = Color(0xFF484852)
val GaugeColors.clusterBezelMid: Color get() = Color(0xFF222228)
val GaugeColors.clusterBezelInner: Color get() = Color(0xFF08080C)
val GaugeColors.clusterFace: Color get() = Color(0xFF0C0C12)
val GaugeColors.clusterFaceDeep: Color get() = Color(0xFF050508)
val GaugeColors.clusterGlow: Color get() = Color(0x44E82127)
val GaugeColors.clusterAmbient: Color get() = Color(0x2864D2FF)
val GaugeColors.clusterHud: Color get() = Color(0xCC0A0A10)
val GaugeColors.clusterHudBorder: Color get() = Color(0x5564D2FF)
val GaugeColors.clusterTickMajor: Color get() = Color(0xEEFFFFFF)
val GaugeColors.clusterTickMinor: Color get() = Color(0x44FFFFFF)
val GaugeColors.clusterTickLabel: Color get() = Color(0x99FFFFFF)
val GaugeColors.clusterArcTrack: Color get() = Color(0x22FFFFFF)
val GaugeColors.clusterArcSafe: Color get() = Color(0xFF34C759)
val GaugeColors.clusterArcWarn: Color get() = Color(0xFFFFCC00)
val GaugeColors.clusterArcDanger: Color get() = Color(0xFFFF3B30)
val GaugeColors.clusterArcActive: Color get() = Color(0xFF3D9EFF)
val GaugeColors.clusterArcAmber: Color get() = Color(0xFFFF8A3D)
val GaugeColors.clusterNeedle: Color get() = Color(0xFFF2F2F7)
val GaugeColors.clusterNeedleGlow: Color get() = Color(0xAAE82127)
val GaugeColors.clusterScanline: Color get() = Color(0x08FFFFFF)
val GaugeColors.panelGlass: Color get() = Color(0xE6121218)
val GaugeColors.panelGlassBorder: Color get() = Color(0x66FFFFFF)
val GaugeColors.panelScrim: Color get() = Color(0xCC050508)
val GaugeColors.accentBlue: Color get() = Color(0xFF64D2FF)
val GaugeColors.accentCyan: Color get() = Color(0xFF5AC8FA)
val GaugeColors.accentOrange: Color get() = Color(0xFFFF9F0A)
val GaugeColors.accentPurple: Color get() = Color(0xFFBF5AF2)
val GaugeColors.accentTeal: Color get() = Color(0xFF40C8E0)
val GaugeColors.metallicHighlight: Color get() = Color(0x55FFFFFF)
val GaugeColors.metallicShadow: Color get() = Color(0xAA000000)
val GaugeColors.powerRegen: Color get() = Color(0xFF30D158)
val GaugeColors.powerDrive: Color get() = Color(0xFF64D2FF)
