#!/usr/bin/env python3
"""
POI speed_camera CSV (data.go.kr) -> SQLDelight INSERT statements generator.

Usage:
  python scripts/poi_csv_to_sql.py --input poi.csv --output speed_camera_inserts.sql

This script is intentionally "best-effort" (header keyword inference) so it can
work across dataset variants.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class SpeedCamera:
    id: str
    latitude: float
    longitude: float
    speedLimitKmh: int
    roadName: str | None
    roadDirection: float | None
    cameraType: str
    sectionLengthM: int | None


def normalize(s: str) -> str:
    return (s or "").strip().lower()


def find_index(headers: list[str], *keys: str) -> int:
    h = [normalize(x) for x in headers]
    for key in keys:
        key_n = normalize(key)
        for i, col in enumerate(h):
            if key_n in col:
                return i
    return -1


def parse_camera_type(raw: str | None) -> str:
    s = (raw or "").strip().lower()
    if "구간시작" in s:
        return "SECTION_START"
    if "구간종료" in s:
        return "SECTION_END"
    if "신호" in s:
        return "SIGNAL"
    if "이동" in s or "mobile" in s:
        return "MOBILE"
    return "FIXED"


def parse_int(s: str | None) -> int | None:
    if s is None:
        return None
    t = s.strip()
    if not t:
        return None
    try:
        return int(float(t))
    except ValueError:
        return None


def parse_float(s: str | None) -> float | None:
    if s is None:
        return None
    t = s.strip()
    if not t:
        return None
    try:
        return float(t)
    except ValueError:
        return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="CSV input file path")
    ap.add_argument("--output", required=True, help="SQL output file path")
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        rows = list(reader)

    if not rows:
        raise SystemExit("Empty CSV")

    headers = rows[0]
    data_rows = rows[1:]

    id_idx = find_index(headers, "관리번호", "카메라관리번호", "id")
    lat_idx = find_index(headers, "위도", "latitude", "lat")
    lng_idx = find_index(headers, "경도", "longitude", "lng", "lon")
    speed_idx = find_index(headers, "제한속도", "속도", "speed")
    road_name_idx = find_index(headers, "도로명", "도로노선", "road")
    road_dir_idx = find_index(headers, "도로노선방향", "방향", "direction", "dir")
    type_idx = find_index(headers, "단속구분", "카메라유형", "유형", "type")
    section_len_idx = find_index(headers, "구간길이", "구간", "section_length", "sectionlen")

    if lat_idx < 0 or lng_idx < 0 or speed_idx < 0:
        raise SystemExit("Missing required columns (위도/경도/제한속도)")

    cameras: list[SpeedCamera] = []
    for cols in data_rows:
        if not cols or len(cols) <= max(lat_idx, lng_idx, speed_idx):
            continue

        lat = parse_float(cols[lat_idx])
        lng = parse_float(cols[lng_idx])
        speed = parse_int(cols[speed_idx])
        if lat is None or lng is None or speed is None:
            continue

        cam_id = ""
        if id_idx >= 0 and id_idx < len(cols) and cols[id_idx].strip():
            cam_id = cols[id_idx].strip()
        else:
            cam_id = f"cam-{lat:.5f}-{lng:.5f}-{speed}"

        road_name = None
        if road_name_idx >= 0 and road_name_idx < len(cols):
            rn = cols[road_name_idx].strip()
            road_name = rn or None

        road_dir = None
        if road_dir_idx >= 0 and road_dir_idx < len(cols):
            road_dir = parse_float(cols[road_dir_idx])

        camera_type_raw = None
        if type_idx >= 0 and type_idx < len(cols):
            camera_type_raw = cols[type_idx]
        camera_type = parse_camera_type(camera_type_raw)

        section_len = None
        if section_len_idx >= 0 and section_len_idx < len(cols):
            section_len = parse_int(cols[section_len_idx])

        cameras.append(
            SpeedCamera(
                id=cam_id,
                latitude=lat,
                longitude=lng,
                speedLimitKmh=speed,
                roadName=road_name,
                roadDirection=road_dir,
                cameraType=camera_type,
                sectionLengthM=section_len,
            )
        )

    def q(v: str | None) -> str:
        if v is None:
            return "NULL"
        esc = v.replace("'", "''")
        return f"'{esc}'"

    with open(args.output, "w", encoding="utf-8") as out:
        out.write("-- Generated by poi_csv_to_sql.py\n")
        out.write("BEGIN TRANSACTION;\n")
        for c in cameras:
            out.write(
                "INSERT OR REPLACE INTO speed_camera("
                "id, latitude, longitude, road_name, road_direction, speed_limit, camera_type, section_length"
                ") VALUES ("
                f"{q(c.id)}, {c.latitude:.8f}, {c.longitude:.8f}, {q(c.roadName)}, "
                f"{('NULL' if c.roadDirection is None else f'{c.roadDirection:.6f}')} , "
                f"{c.speedLimitKmh}, {q(c.cameraType)}, {('NULL' if c.sectionLengthM is None else c.sectionLengthM)}"
                ");\n"
            )
        out.write("COMMIT;\n")

    print(f"Wrote {len(cameras)} inserts to {args.output}")


if __name__ == "__main__":
    main()

